apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 3000
      # Hardcoded an explicit port mapping 
      # (Choose any free port between 30000-32767). This stops K8s from 
      # randomly assigning a new port every time you drop the stack.
      nodePort: 31000 
  type: NodePort